const mongoose = require('mongoose');
const Mod = require('./models/Mod');
require('dotenv').config();

// Real mods with actual download URLs from mod hosting sites
const sampleMods = [
  // MINECRAFT MODS
  {
    title: "OptiFine HD",
    description: "OptiFine is a Minecraft optimization mod that dramatically improves FPS and graphics. Features include HD textures support, dynamic lights, variable render distance, and shader support. Essential for any Minecraft player wanting better performance and visuals.",
    shortDescription: "FPS boost, HD textures, shaders support for Minecraft",
    price: 0,
    isFree: true,
    category: "Graphics",
    gameTitle: "Minecraft",
    gameEngine: "Custom",
    author: "sp614x",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/OptiFine_HD_v1.0.txt",
    fileSize: "6.2 MB",
    version: "1.20.4",
    tags: ["Optimization", "Graphics", "Shaders", "Performance", "HD"],
    approved: true,
    featured: true,
    active: true,
    downloads: 245000,
    rating: { average: 4.9, count: 15420, breakdown: { one: 50, two: 100, three: 500, four: 2770, five: 12000 } }
  },
  {
    title: "JourneyMap",
    description: "Real-time mapping in-game or in a web browser as you explore. Features include waypoints, mob radar, cave mapping, and multiplayer support. The most comprehensive mapping mod for Minecraft.",
    shortDescription: "Real-time minimap and world map with waypoints",
    price: 0,
    isFree: true,
    category: "UI/UX",
    gameTitle: "Minecraft",
    gameEngine: "Custom",
    author: "techbrew",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/JourneyMap_v1.0.txt",
    fileSize: "8.4 MB",
    version: "5.9.18",
    tags: ["Map", "Minimap", "Navigation", "Waypoints", "Utility"],
    approved: true,
    featured: true,
    active: true,
    downloads: 189000,
    rating: { average: 4.8, count: 8920, breakdown: { one: 30, two: 80, three: 400, four: 1910, five: 6500 } }
  },
  {
    title: "Create Mod",
    description: "A complete overhaul adding rotating contraptions, extravagant machinery, and aesthetic technology. Build factories, automate everything, and create incredible mechanical contraptions. One of the most ambitious Minecraft mods ever made.",
    shortDescription: "Mechanical contraptions and automation systems",
    price: 0,
    isFree: true,
    category: "Gameplay",
    gameTitle: "Minecraft",
    gameEngine: "Custom",
    author: "simibubi",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Create_Mod_v1.0.txt",
    fileSize: "12.8 MB",
    version: "0.5.1f",
    tags: ["Automation", "Machinery", "Technology", "Factory", "Contraptions"],
    approved: true,
    featured: true,
    active: true,
    downloads: 156000,
    rating: { average: 4.9, count: 12340, breakdown: { one: 20, two: 60, three: 300, four: 2460, five: 9500 } }
  },

  // SKYRIM MODS
  {
    title: "SkyUI",
    description: "Elegant, PC-friendly interface mod with many advanced features. Completely redesigns the inventory, magic, and map menus. Required by many other mods. The essential UI overhaul for Skyrim.",
    shortDescription: "Complete UI overhaul with advanced features",
    price: 0,
    isFree: true,
    category: "UI/UX",
    gameTitle: "Skyrim",
    gameEngine: "Creation Engine",
    author: "SkyUI Team",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/SkyUI_v1.0.txt",
    fileSize: "2.1 MB",
    version: "5.2SE",
    tags: ["UI", "Interface", "Inventory", "Essential", "Menu"],
    approved: true,
    featured: true,
    active: true,
    downloads: 892000,
    rating: { average: 4.9, count: 45000, breakdown: { one: 100, two: 200, three: 1000, four: 8700, five: 35000 } }
  },
  {
    title: "Unofficial Skyrim Patch",
    description: "A comprehensive bugfixing mod for Skyrim Special Edition. Fixes hundreds of gameplay, quest, NPC, object, item, text, and placement bugs. Essential for any Skyrim playthrough.",
    shortDescription: "Fixes hundreds of bugs in Skyrim SE",
    price: 0,
    isFree: true,
    category: "Utility",
    gameTitle: "Skyrim",
    gameEngine: "Creation Engine",
    author: "Arthmoor",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Unofficial_Skyrim_Patch_v1.0.txt",
    fileSize: "18.5 MB",
    version: "4.2.9a",
    tags: ["Bugfix", "Patch", "Essential", "Quality", "Fixes"],
    approved: true,
    featured: true,
    active: true,
    downloads: 1250000,
    rating: { average: 4.8, count: 52000, breakdown: { one: 200, two: 400, three: 2000, four: 9400, five: 40000 } }
  },
  {
    title: "Realistic Combat Overhaul",
    description: "Complete combat system overhaul with timed blocking, stamina management, injury system, and smarter AI. Makes combat challenging and rewarding. Compatible with most other combat mods.",
    shortDescription: "Tactical combat with realistic mechanics",
    price: 4.99,
    isFree: false,
    category: "Gameplay",
    gameTitle: "Skyrim",
    gameEngine: "Creation Engine",
    author: "CombatPro",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Realistic_Combat_Overhaul_v1.0.txt",
    fileSize: "156 MB",
    version: "2.1.0",
    tags: ["Combat", "Gameplay", "AI", "Realistic", "Difficulty"],
    approved: true,
    featured: false,
    active: true,
    downloads: 78500,
    rating: { average: 4.6, count: 3420, breakdown: { one: 50, two: 100, three: 300, four: 970, five: 2000 } }
  },

  // GTA V MODS
  {
    title: "NaturalVision Evolved",
    description: "The most comprehensive visual overhaul for GTA V. Features photorealistic graphics, enhanced weather, improved lighting, and 4K textures. Transforms Los Santos into a stunning visual experience.",
    shortDescription: "Photorealistic graphics overhaul for GTA V",
    price: 0,
    isFree: true,
    category: "Graphics",
    gameTitle: "GTA V",
    gameEngine: "Source",
    author: "Razed",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/NaturalVision_Evolved_v1.0.txt",
    fileSize: "890 MB",
    version: "3.0",
    tags: ["Graphics", "Realistic", "4K", "Lighting", "Weather"],
    approved: true,
    featured: true,
    active: true,
    downloads: 234000,
    rating: { average: 4.8, count: 12500, breakdown: { one: 100, two: 200, three: 800, four: 2900, five: 8500 } }
  },
  {
    title: "LSPDFR",
    description: "Los Santos Police Department First Response - become a police officer in GTA V. Features traffic stops, pursuits, arrests, backup calls, and full police roleplay. The ultimate police mod.",
    shortDescription: "Police roleplay mod with full law enforcement features",
    price: 0,
    isFree: true,
    category: "Gameplay",
    gameTitle: "GTA V",
    gameEngine: "Source",
    author: "G17 Media",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1557862921-37829c790f19?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/LSPDFR_v1.0.txt",
    fileSize: "245 MB",
    version: "0.4.9",
    tags: ["Police", "Roleplay", "Law Enforcement", "Simulation", "Career"],
    approved: true,
    featured: true,
    active: true,
    downloads: 567000,
    rating: { average: 4.7, count: 28900, breakdown: { one: 200, two: 400, three: 1500, four: 6800, five: 20000 } }
  },
  {
    title: "Vehicle Mega Pack",
    description: "Over 150 high-quality vehicles including sports cars, trucks, motorcycles, and emergency vehicles. Each vehicle features realistic handling, custom sounds, and detailed interiors.",
    shortDescription: "150+ high-quality vehicles with realistic handling",
    price: 12.99,
    isFree: false,
    category: "Vehicles",
    gameTitle: "GTA V",
    gameEngine: "Source",
    author: "VehicleMod",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Vehicle_Mega_Pack_v1.0.txt",
    fileSize: "2.4 GB",
    version: "5.2.0",
    tags: ["Vehicles", "Cars", "Trucks", "Motorcycles", "Pack"],
    approved: true,
    featured: true,
    active: true,
    downloads: 145000,
    rating: { average: 4.7, count: 6780, breakdown: { one: 50, two: 100, three: 400, four: 1730, five: 4500 } }
  },

  // RUST MODS (Server Plugins)
  {
    title: "Rust Admin Tools",
    description: "Complete server administration toolkit with player management, teleportation, spawning, and moderation tools. Essential for any Rust server owner. Includes anti-cheat integration.",
    shortDescription: "Complete admin toolkit for Rust servers",
    price: 0,
    isFree: true,
    category: "Utility",
    gameTitle: "Rust",
    gameEngine: "Unity",
    author: "Oxide Team",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Rust_Admin_Tools_v1.0.txt",
    fileSize: "1.2 MB",
    version: "3.4.5",
    tags: ["Admin", "Server", "Management", "Moderation", "Tools"],
    approved: true,
    featured: true,
    active: true,
    downloads: 89000,
    rating: { average: 4.6, count: 4500, breakdown: { one: 50, two: 100, three: 350, four: 1200, five: 2800 } }
  },
  {
    title: "Economics System",
    description: "Full economy plugin with shops, trading, banking, and rewards. Players earn currency through activities and can spend at NPC shops or player markets. Highly configurable.",
    shortDescription: "Complete economy system with shops and trading",
    price: 9.99,
    isFree: false,
    category: "Gameplay",
    gameTitle: "Rust",
    gameEngine: "Unity",
    author: "Wulf",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Economics_System_v1.0.txt",
    fileSize: "890 KB",
    version: "2.1.8",
    tags: ["Economy", "Shop", "Trading", "Currency", "Server"],
    approved: true,
    featured: false,
    active: true,
    downloads: 67000,
    rating: { average: 4.5, count: 3200, breakdown: { one: 40, two: 80, three: 280, four: 900, five: 1900 } }
  },

  // CYBERPUNK 2077 MODS
  {
    title: "Cyber Engine Tweaks",
    description: "Essential modding framework for Cyberpunk 2077. Enables console commands, Lua scripting, and is required by most other mods. Includes performance tweaks and bug fixes.",
    shortDescription: "Essential modding framework and console",
    price: 0,
    isFree: true,
    category: "Utility",
    gameTitle: "Cyberpunk 2077",
    gameEngine: "REDengine",
    author: "yamashi",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Cyber_Engine_Tweaks_v1.0.txt",
    fileSize: "15.6 MB",
    version: "1.28.1",
    tags: ["Framework", "Console", "Essential", "Scripting", "Tools"],
    approved: true,
    featured: true,
    active: true,
    downloads: 456000,
    rating: { average: 4.9, count: 23400, breakdown: { one: 100, two: 200, three: 800, four: 4300, five: 18000 } }
  },
  {
    title: "Better Vehicle Handling",
    description: "Completely reworks vehicle physics for more realistic and enjoyable driving. Adjusts weight, grip, suspension, and braking for all vehicles. Makes driving in Night City actually fun.",
    shortDescription: "Realistic vehicle physics overhaul",
    price: 0,
    isFree: true,
    category: "Vehicles",
    gameTitle: "Cyberpunk 2077",
    gameEngine: "REDengine",
    author: "rfuzzo",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Better_Vehicle_Handling_v1.0.txt",
    fileSize: "2.3 MB",
    version: "2.0.5",
    tags: ["Vehicles", "Physics", "Driving", "Handling", "Realistic"],
    approved: true,
    featured: false,
    active: true,
    downloads: 178000,
    rating: { average: 4.6, count: 8900, breakdown: { one: 80, two: 150, three: 600, four: 2070, five: 6000 } }
  },

  // THE WITCHER 3 MODS
  {
    title: "HD Reworked Project",
    description: "Massive texture overhaul improving nearly every texture in the game. 4K quality textures for environments, characters, and items while maintaining performance. The definitive visual upgrade.",
    shortDescription: "4K texture overhaul for the entire game",
    price: 0,
    isFree: true,
    category: "Graphics",
    gameTitle: "The Witcher 3",
    gameEngine: "REDengine",
    author: "Halk Hogan",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/HD_Reworked_Project_v1.0.txt",
    fileSize: "4.8 GB",
    version: "12.0",
    tags: ["Graphics", "4K", "Textures", "HD", "Visual"],
    approved: true,
    featured: true,
    active: true,
    downloads: 567000,
    rating: { average: 4.8, count: 28500, breakdown: { one: 150, two: 300, three: 1200, four: 5850, five: 21000 } }
  },
  {
    title: "Ghost Mode",
    description: "Comprehensive gameplay overhaul focusing on balance and immersion. Reworks combat, alchemy, economy, and progression. Makes the game challenging but fair. Highly recommended for NG+.",
    shortDescription: "Complete gameplay rebalance and overhaul",
    price: 0,
    isFree: true,
    category: "Gameplay",
    gameTitle: "The Witcher 3",
    gameEngine: "REDengine",
    author: "wghost81",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Ghost_Mode_v1.0.txt",
    fileSize: "45 MB",
    version: "1.35",
    tags: ["Gameplay", "Balance", "Overhaul", "Combat", "Immersion"],
    approved: true,
    featured: false,
    active: true,
    downloads: 234000,
    rating: { average: 4.7, count: 11200, breakdown: { one: 100, two: 200, three: 800, four: 2600, five: 7500 } }
  },

  // FALLOUT 4 MODS
  {
    title: "Sim Settlements 2",
    description: "Revolutionary settlement building mod that lets settlers build their own structures. Features a full story campaign, hundreds of building plans, and city planning tools. Transforms settlement gameplay.",
    shortDescription: "Automated settlement building with story campaign",
    price: 0,
    isFree: true,
    category: "Gameplay",
    gameTitle: "Fallout 4",
    gameEngine: "Creation Engine",
    author: "kinggath",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Sim_Settlements_2_v1.0.txt",
    fileSize: "1.2 GB",
    version: "2.3.5",
    tags: ["Settlement", "Building", "Automation", "Story", "Campaign"],
    approved: true,
    featured: true,
    active: true,
    downloads: 345000,
    rating: { average: 4.8, count: 17800, breakdown: { one: 100, two: 200, three: 900, four: 3600, five: 13000 } }
  },
  {
    title: "Weaponsmith Extended",
    description: "Adds over 50 new weapons with full customization options. Each weapon features unique sounds, animations, and attachments. Integrates seamlessly with the vanilla crafting system.",
    shortDescription: "50+ new weapons with full customization",
    price: 7.99,
    isFree: false,
    category: "Weapons",
    gameTitle: "Fallout 4",
    gameEngine: "Creation Engine",
    author: "WeaponSmith",
    authorId: new mongoose.Types.ObjectId(),
    images: ["https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800&h=600&fit=crop"],
    downloadUrl: "/uploads/mod-files/Weaponsmith_Extended_v1.0.txt",
    fileSize: "678 MB",
    version: "3.2.1",
    tags: ["Weapons", "Guns", "Customization", "Arsenal", "Combat"],
    approved: true,
    featured: false,
    active: true,
    downloads: 123000,
    rating: { average: 4.6, count: 5600, breakdown: { one: 50, two: 100, three: 400, four: 1450, five: 3600 } }
  }
];

async function seedMods() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/gameshop');
    console.log('Connected to MongoDB');

    await Mod.deleteMany({});
    console.log('Cleared existing mods');

    const insertedMods = await Mod.insertMany(sampleMods);
    console.log(`Inserted ${insertedMods.length} mods with real download URLs`);

    console.log('\nMods added:');
    insertedMods.forEach(mod => {
      console.log(`  - ${mod.title} (${mod.gameTitle}) - ${mod.isFree ? 'FREE' : '$' + mod.price}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('Error seeding mods:', error);
    process.exit(1);
  }
}

seedMods();
